% Script generated by Brainstorm v3.1 (17-Dec-2013)

function brainstorm_subject_sources_export2spm_volume(settings_path, protocol_name, source_file, outputfolder, interval, outtag, varargin)

    iProtocol = brainstorm_protocol_open(protocol_name);
    protocol = bst_get('ProtocolInfo');
    brainstorm_data_path = protocol.STUDIES;
    
    % load configuration file
    [path,name_noext,ext] = fileparts(settings_path);
    addpath(path);    eval(name_noext);

    timedownsample=1;
    voldownsample=2;
    options_num=size(varargin,2);
    for opt=1:options_num
        switch varargin{opt}
            case 'timedownsample'
                opt=opt+1;
                timedownsample=varargin{opt};
            case 'voldownsample'
                opt=opt+1;
                voldownsample=varargin{opt};                
        end
    end


    % Input files
    sFiles = {source_file};
    RawFiles = {outputfolder};

    % Start a new report
    bst_report('Start', sFiles);

    % Process: Export to SPM8 (volume)
    sFiles = bst_process(...
        'CallProcess', 'process_export_spmvol', ...
        sFiles, [], ...
        'outputdir', {RawFiles{1}, 'Nifti1'}, ...
        'filetag', outtag, ...
        'isconcat', 1, ...
        'timewindow', interval, ...
        'timedownsample', timedownsample, ...
        'timemethod', 1, ...
        'voldownsample', voldownsample, ...
        'isabs', 1, ...
        'iscut', 1);

    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);

end

