% Script generated by Brainstorm v3.1 (10-May-2013)

function sFiles = brainstorm_group_stats_2cond_pairedttest(protocol_name, cond1, cond2,  analysis_type, abs_type, subjects_list)

    iProtocol = brainstorm_protocol_open(protocol_name);
    protocol = bst_get('ProtocolInfo');
    brainstorm_data_path = protocol.STUDIES;
    
    
    
    
    
    
    
    len_subj=length(subjects_list);
    FileNamesA=cell(1,len_subj);
    FileNamesB=cell(1,len_subj);
    
    for nsubj=1:len_subj
       FileNamesA{nsubj}=fullfile(subjects_list{nsubj}, cond1, [analysis_type '.mat']);
       FileNamesB{nsubj}=fullfile(subjects_list{nsubj}, cond2, [analysis_type '.mat']);
    end
 
    % Start a new report
    bst_report('Start', FileNamesA);

    % Process: paired t-test
    sFiles = bst_process(...
        'CallProcess', 'process_ttest_paired', ...
        FileNamesA, FileNamesB, ...
        'abs_type', abs_type);  % D = abs(A)-abs(B)   - Default

    
    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    
    src_filename=fullfile(brainstorm_data_path, sFiles(1).FileName);
    dest_filename=fullfile(brainstorm_data_path, '@inter', ['presults_' cond1 '_' cond2 '_' analysis_type '.mat']);
    movefile(src_filename, dest_filename, 'f');
    
    db_reload_studies(sFiles(1).iStudy);
end
