function [template] = initialise_params(structure_name)
% It initialises the parameters according to the input structuer name.
    switch lower(structure_name)
        case 'globaldata'
            template = struct(...
                'main_panel', [], ...
                'top_panel', [], ...
                'main_tabs', struct(), ...
                ...
                'textFields', struct( ...
                    'project', struct(...
                        'paths', struct(...
                            'project', [], ...
                            'original_data', [], ...
                            'input_epochs', [], ...
                            'output_epochs', [], ...
                            'results', [], ...
                            'emg_epochs', [], ...
                            'emg_epochs_mat', [], ...
                            'tf', [], ...
                            'cluster_projection_erp', [], ...
                            'batches', [], ...
                            'spmsources', [], ...
                            'spmstats', [], ...
                            'spm', [], ...
                            'eeglab', [], ...
                            'brainstorm', [] ...
                            ) ...
                        ) ...
                    ), ...
                ...
                'button_test', struct(...
                    'label', '', ...
                    'value', []), ...
                ...
                'editable_path', struct(...
                    'label', ''));
                
            path_main = which('gui');
            template.path_main = path_main(1:end-5);
            template.path_icons = strcat(template.path_main, 'icons\');
    end

end

