% Script generated by Brainstorm v3.1 (10-May-2013)

function sFiles = proj_brainstorm_group_stats_2cond_pairedttest(project, cond1, cond2, analysis_type, varargin)

    subjects_list   = project.subjects.list;
    abs_type        = project.brainstorm.stats.ttest_abstype;

    for v=1:2:length(varargin)
        if ~isempty(varargin{v+1})        
            assign(varargin{v}, varargin{v+1});
        end
    end
    
    sFiles = brainstorm_group_stats_2cond_pairedttest(project.brainstorm.db_name, cond1, cond2,  analysis_type, abs_type, subjects_list);
end
