% orient:       fixed, free, loose
% norm:         wmne, dspm, sloreta
% tag:          whichever string
% loose_value

function  proj_brainstorm_subject_scout_fc(project,  varargin)

iProtocol               = brainstorm_protocol_open(project.brainstorm.db_name);
protocol                = bst_get('ProtocolInfo');
brainstorm_data_path    = protocol.STUDIES;




list_select_subjects    = project.subjects.list;

for par=1:2:length(varargin)
    switch varargin{par}
        case { 'list_select_subjects', ...
                }
            
            if isempty(varargin{par+1})
                continue;
            else
                assign(varargin{par}, varargin{par+1});
            end
    end
end

if not(isfield(project.brainstorm,'condition_names'))
    project.brainstorm.condition_names = project.epoching.condition_names;
    project.brainstorm.numcond         = project.epoching.numcond;
end


condition_names             =  project.brainstorm.condition_names;

tot_mfc = length(project.brainstorm.fc.selected_measure_list); % measures of functional connectivity to be computed
for nmfc = 1:tot_mfc
    current_measure = project.brainstorm.fc.selected_measure_list{nmfc};
    current_bs_process = ['process_', current_measure];
    disp(['compute ' current_measure, 'using ', current_bs_process, ' process']);
    
    for t=1:length(project.brainstorm.fc.scout_tag_list)
        tag         = project.brainstorm.fc.scout_tag_list{t};
        input_file  = [project.brainstorm.average_file_name '.mat'];   .... e.g. 'data_average.mat'
            
    for cond=1:project.brainstorm.numcond
        cond_files = brainstorm_results_get_from_subjectslist_by_tag(list_select_subjects, condition_names{cond}, input_file, tag);
        for s=1:length(cond_files)
            result_file = fullfile(project.paths.project, project.brainstorm.db_name, 'data', cond_files{s});
            ...for ntw = 1:length(project.postprocess.ersp.design(1).group_time_windows)
                
        switch current_measure
            
            case 'corr1n'
                brainstorm_subject_scout_fc_corr1n(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.corr1n.scouttime,...
                    project.brainstorm.fc.corr1n.scalarprod,...
                    project.brainstorm.fc.corr1n.outputmode,...
                    project.postprocess.ersp.design(1).group_time_windows...
                    ...[...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).min,...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).max...
                    ...]...
                    );
            case 'corr1n_time'
                brainstorm_subject_scout_fc_corr1n_time(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.corr1n.scouttime,...
                    project.brainstorm.fc.corr1n.scalarprod,...
                    project.brainstorm.fc.corr1n.outputmode,...
                    [...
                    project.epoching.epo_st.s,...
                    project.epoching.epo_end.s...
                    ],...
                    project.brainstorm.fc.cohere1n_time.win,...
                    project.brainstorm.fc.cohere1n_time.overlap...
                    );
            
            case 'cohere1n'
                brainstorm_subject_scout_fc_cohere1n(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.cohere1n.scouttime,...
                    project.brainstorm.fc.cohere1n.removeevoked,...
                    project.brainstorm.fc.cohere1n.cohmeasure,...
                    project.study.ersp.fmax_analysis,...
                    project.brainstorm.fc.cohere1n.outputmode,...
                    project.postprocess.ersp.design(1).group_time_windows...
                    ...[...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).min,...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).max...
                    ...]...
                    );
                %% nota: vanno ristrutturate per conciliare quelle che girano su time window (ciclo su time window qui e non nella funzione!!)
                % con quelle che sono time resolved, quindi NON
                % ciclano sulle time window, POSSIBILITA': INTEGRARE
                % IL CICLO NELLA FUNZIONE
            case 'cohere1n_time'
                brainstorm_subject_scout_fc_cohere1n_time(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.cohere1n_time.scouttime,...
                    project.brainstorm.fc.cohere1n_time.removeevoked,...
                    project.brainstorm.fc.cohere1n_time.cohmeasure,...
                    project.study.ersp.fmax_analysis,...
                    [...
                    project.epoching.epo_st.s,...
                    project.epoching.epo_end.s...
                    ],...
                    project.brainstorm.fc.cohere1n_time.win,...
                    project.brainstorm.fc.cohere1n_time.overlap...
                    );
                
                
            case 'granger1n'
                brainstorm_subject_scout_fc_granger1n(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.granger1n.scouttime,...
                    project.brainstorm.fc.granger1n.removeevoked,...
                    project.brainstorm.fc.granger1n.outputmode,...
                     project.postprocess.ersp.design(1).group_time_windows...
                    ...[...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).min,...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).max...
                    ...]...
                    );
                
            case 'spgranger1n'
                brainstorm_subject_scout_fc_spgranger1n(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.spgranger1n.scouttime,...
                    project.brainstorm.fc.spgranger1n.removeevoked,...
                    project.study.ersp.fmax_analysis,...
                    project.brainstorm.fc.spgranger1n.outputmode,...
                    project.postprocess.ersp.design(1).group_time_windows...
                    ...[...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).min,...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).max...
                    ...]...
                    );
                
            case 'plv1n'
                brainstorm_subject_scout_fc_plv1n(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.plv1n.scouttime,...
                    project.brainstorm.fc.plv1n.freqbands,...
                    project.study.fc.plv1n.mirror,...
                    project.study.fc.plv1n.keeptime,...
                    project.study.fc.plv1n.plvmeasure,...
                    project.brainstorm.fc.plv1n.outputmode,...
                    project.postprocess.ersp.design(1).group_time_windows...
                    ...[...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).min,...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).max...
                    ...]...
                    );
                
            case 'pte1n'
                brainstorm_subject_scout_fc_plv1n(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.pte1n.scouttime,...
                    project.brainstorm.fc.pte1n.freqbands,...
                    project.study.fc.pte1n.mirror,...
                    project.study.fc.plv1n.normalized,...                   
                    project.brainstorm.fc.plv1n.outputmode,...
                    project.postprocess.ersp.design(1).group_time_windows...
                    ...[...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).min,...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).max...
                    ...]...
                    );
                
            case 'aec1n'
                brainstorm_subject_scout_fc_aec1n(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.aec1n.scouttime,...
                    project.brainstorm.fc.aec1n.freqbands,...
                    project.brainstorm.fc.aec1n.isorth,...
                    project.brainstorm.fc.aec1n.outputmode,...
                    project.postprocess.ersp.design(1).group_time_windows...
                    ...[...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).min,...
                    ...project.postprocess.ersp.design(1).group_time_windows(ntw).max...
                    ...]...
                    );
                
                case 'pac'
                brainstorm_subject_scout_fc_pac(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.pac.scouttime,...
                    project.brainstorm.fc.pac.nesting,...
                    project.brainstorm.fc.pac.nested,...
                    project.brainstorm.fc.pac.numfreqs,...
                    project.brainstorm.fc.pac.parallel,...
                    project.brainstorm.fc.pac.ismex,...
                    project.brainstorm.fc.pac.max_block_size,...
                    project.brainstorm.fc.pac.avgoutput,...
                    project.brainstorm.fc.pac.savemax,...
                    project.postprocess.ersp.design(1).group_time_windows...                   
                    );
                
            case 'tpac'
                brainstorm_subject_scout_fc_pac(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.tpac.nesting,...
                    project.brainstorm.fc.tpac.nested,...
                    project.brainstorm.fc.tpac.fa_type,...
                    project.brainstorm.fc.tpac.winLen,...
                    project.brainstorm.fc.tpac.target_res,...
                    project.brainstorm.fc.tpac.max_block_size,...
                    project.brainstorm.fc.tpac.avgoutput,...
                    project.brainstorm.fc.tpac.margin,...
                    [...
                    project.epoching.epo_st.s,...
                    project.epoching.epo_end.s...
                    ]...
                    );
                
           case 'canoltymap'
                brainstorm_subject_scout_fc_canoltymap(...
                    project.brainstorm.db_name, ...
                    result_file, ...
                    tag,...
                    project.brainstorm.postprocess.downsample_atlasname,...
                    project.brainstorm.postprocess.scouts_names,...
                    project.brainstorm.postprocess.scoutfunc_str,...
                    project.brainstorm.fc.canoltymap.scouttime,...
                    project.brainstorm.fc.canoltymap.epochtime,...
                    project.brainstorm.fc.canoltymap.lowfreq,...
                    project.brainstorm.fc.canoltymap.max_block_size,...
                    project.brainstorm.fc.canoltymap.save_erp,...
                    project.postprocess.ersp.design(1).group_time_windows...                   
                    );
                
              
                
                
                
        end
        ...end
            
        end
    end
    end
end
end
