% Script generated by Brainstorm v3.1 (10-May-2013)

function sFiles = brainstorm_group_stats_2cond_ttest(protocol_name, cond1, cond2, analysis_type, var_type, subjects_list)

    iProtocol = brainstorm_protocol_open(protocol_name);
    protocol = bst_get('ProtocolInfo');
    brainstorm_data_path = protocol.STUDIES;
    
    if (strcmp(var_type,'equal_var'))
        var_type=1;
    else
        var_type=2;
    end
    
    len_subj=length(subjects_list);
    FileNamesA=cell(1,len_subj);
    FileNamesB=cell(1,len_subj);
    
    for nsubj=1:len_subj
       FileNamesA{nsubj}=fullfile(subjects_list{nsubj}, cond1, [analysis_type '.mat']);
       FileNamesB{nsubj}=fullfile(subjects_list{nsubj}, cond2, [analysis_type '.mat']);
    end
 
    % Start a new report
    bst_report('Start', FileNamesA);

    % Process: t-test [unequal var, avg(abs)]
    sFiles = bst_process(...
        'CallProcess', 'process_ttest', ...
        FileNamesA, FileNamesB, ...
        'testtype', var_type, ...
        'avg_func', 2);  % <HTML>Average of absolute values:  <FONT color="#777777">mean(abs(x))</FONT>

    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    
    src_filename=fullfile(brainstorm_data_path, sFiles(1).FileName);
    dest_filename=fullfile(brainstorm_data_path, '@inter', ['presults_' cond1 '_' cond2 '_' analysis_type '.mat']);
    movefile(src_filename, dest_filename, 'f');
    
    db_reload_studies(sFiles(1).iStudy);
end
